### ISSUE TITLE
conflict with built-in extension

### ISSUE THREAD

**Issue by yi-Xu-0100** [RechInformatica/rech-editor-batch#10]
![image](https://user-images.githubusercontent.com/25523606/90307824-aa6b9400-df0c-11ea-9cfa-9717cd29cc50.png)

**Comment by GustavoASC** [comment]
Hello @yi-Xu-0100, how are you?
Thanks for opening this issue!

This message is expected because VSCode ships a built-in extension for batch files which conflicts with Rech Batch extension.
The 'conflict' word means that built-in extension defines **REM** (upper-case) as comment delimiter, whilst Rech Batch defines **rem** (lowercase) for that.

Depending on the order extensions are activated, which is arbritary, one execution would use 'REM' and other execution would use 'rem'. Disabling built-in extension ensures this problem won't happen.

We will improve this message to make it more clear.

**Comment by yi-Xu-0100** [comment]
Thank you for your reply to let me know the difference between these two plugins.

**Comment by GustavoASC** [comment]
Reopening issue to link the PR with improvements on the message, in order to provide a better understanding.
